baseURL = 'https://www.curtisjewell.website/'
title = 'Differently Drumming'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'rss']
noBuildLock = true

[params]
  title = 'Differently Drumming' 
  description = 'The blog of a complicated person'
  message = 'COMING SOON!'
  release = 'July 12, 2025'
  background = '' 

  socialIcons = [
    {name = 'twitter', url = 'https://twitter.com/CSJewell'},    
    {name = 'facebook', url = 'https://facebook.com/csjewell'},    
    {name = 'github', url = 'https://github.com/CSJewell'},    
    {name = 'instagram', url = 'https://instagram.com/csjewell5'},    
    {name = 'linkedin', url = 'https://linkedin.com/in/curtissjewell'},    
  ] 

[params.twitter]
    enable = true 
    username = 'CSJewell'

[languages]
  [languages.en]
    languageCode = 'en-019'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1


