name = "curtisjewell-website"
compatibility_date = "2025-07-06"

[assets]
directory = "./public"

[build]
command = "hugo"

routes = [
  { pattern = "curtisjewell.website", custom_domain = true },
  { pattern = "www.curtisjewell.website", custom_domain = true }
]
